### ISSUE TITLE
jsp파일별 용도와 시멘틱에 구현해야할 기능 총 정리

### ISSUE THREAD

**Issue by Cheonrihyang** [Cheonrihyang/DengDeng#12]
**<h1>community</h1>**
**community_event_participate_write.jsp**
이벤트 참여 글쓰기
>nav : 게시판 이동 메뉴
section : article,nav의 집합
section-article : 글 쓰는 공간
section-nav : 동작 버튼이 위치하는 곳

**community_event_participate.jsp**
이벤트 참여
>nav : 게시판 이동 메뉴
section : article,div,nav의 집합
section-article : div의 집합
section-article-div : 유저가 등록한 이벤트 참여 글을 출력하는 박스들
section-nav(첫 번째) : 동작 버튼이 위치하는 곳
section-nav(두 번째) : 페이지 이동이 위치하는 곳

**community_event.jsp**
이벤트
>section : header,article,div의 집합
section-header : 이벤트 글씨가 위치하는 곳
section-article : div의 집합
section-article-div : 이벤트를 출력하는 박스들

**community_FAQ.jsp**
FAQ
>nav : 게시판 이동 메뉴
section : header,article,nav의 집합
section-header : 검색 창이 위치하는 곳
section-article : 게시판 목록이 출력 되는 곳
section-nav : 페이지 이동이 위치하는 곳

**community_notice.jsp**
공지
>nav : 게시판 이동 메뉴
section : header,article,nav의 집합
section-header : 검색 창이 위치하는 곳
section-article : 게시판 목록이 출력 되는 곳
section-nav : 페이지 이동이 위치하는 곳

**community_QNA_write.jsp**
QNA글쓰기
>nav : 게시판 이동 메뉴
section : article,nav의 집합
section-article : 글 쓰는 공간
section-nav : 동작 버튼이 위치하는 곳

**community_QNA.jsp**
QNA
>nav : 게시판 이동 메뉴
section : header,article,div의 집합
section-header : 검색 창이 위치하는 곳
section-article : 게시판 목록이 출력 되는 곳
section-nav : 페이지 이동이 위치하는 곳

**Comment by L-JUYEON** [comment]
[시멘틱 기능 정리-이주연.txt](https://github.com/Cheonrihyang/DengDeng/files/15375097/-.txt)

**Comment by L-JUYEON** [comment]
id.jsp  
아이디찾기
section-header :  아이디찾기 글씨가 위치하는 곳
section-article : 고객정보 입력하는곳 , 동작버튼 1개 
section-nav : 동작버튼 5개가 위치하는곳 
	    
password.jsp   
비밀번호 찾기
section-header :  비밀번호찾기 글씨가 위치하는 곳
section-article : 고객정보 입력하는곳,  동작버튼 1개
section-nav : 동작버튼 4개가 위치하는 곳

login.jsp	 
로그인
section-header :  로그인 글씨가 위치하는 곳
section-article : 고객정보 입력하는 곳
section-nav : 동작버튼 4개가 위치하는곳

index.jsp  
메인페이지
header : 페이지 이동 메뉴 
section-article :  상품 슬라이드 배너
section-article(12개) : 상품을 출력하는 곳

**Comment by SanghyeonLee97** [comment]
### mypage
**[mypage 공통 기능]**

> header-article: 해당 게시판 이동 링크
> section-aside: 해당 게시판 이동 링크


**mypage_main.jsp**
메인페이지: 주문/배송
> section-section-header:		해당 페이지의 제목 (ex. 주문/배송)
> section-section-nav:		조회하는 기간
> section-section-article:		주문/배송 물품에 대한 정보

**mypage_review.jsp** 
리뷰 페이지
> section-section-header:	해당 페이지의 제목 (ex. 리뷰)
> section-section-nav:		조회하는 기간
> section-section-article:	내가 구매한 물품에 대한 정보

**mypage_reserve.jsp**
적립금 페이지
> section-section-header:	해당 페이지의 제목 (ex. 적립금)
> section-section-nav:		조회할 내용 필터
> section-section-article:	적립금 내역에 관한 리스트들

**mypage_coupon.jsp**
쿠폰 페이지
> section-section-header:	해당 페이지의 제목 (ex. 쿠폰)
> section-section-article:	쿠폰 내역에 관한 리스트들

**mypage_dibs.jsp**
하트(찜) 페이지
> section-section-header:		해당 페이지의 제목 (ex. 하트(찜))
> section-section-article:		찜한 내역

**mypage_recently_viewed_items.jsp** 
최근 본 상품 페이지
> section-section-header:		해당 페이지의 제목 (ex. 최근 본 상품)
> section-section-article:		최근 본 상품 리스트

**mypage_cancel_refund.jsp**
취소/반품/교환 페이지
> section-section-header:		해당 페이지의 제목 (ex. 취소/반품/교환)
> section-section-article:		취소/반품/교환 물품에 대한 정보

**mypage_product_inqquiry.jsp**
1:1 문의 페이지
> section-section-header:		해당 페이지의 제목 (ex. 1:1 문의)
> section-section-nav:			조회하는 기간
> section-section-article:		문의 내역 리스트

**mypage_edit_info.jsp**
회원정보 수정 페이지
> section-section-header:		해당 페이지의 제목 (ex. 회원정보 수정)
> section-section-article:		회원정보 수정, 반려견 정보

**mypage_delivery_address.jsp**
배송지 관리 페이지
> section-section-header:		해당 페이지의 제목 (ex. 배송지 관리)
> section-section-article:		각각의 배송지를 보여주는 구역

**mypage_order_payment.jsp**
결제 페이지
> main-header:				해당 페이지의 제목 (ex. 주문/결제)
> section-section-article(1)		주문자의 정보, 배송지
> section-section-article(2)		할인 및 적립금
> section-section-article(3)		결제 수단
> section-aside				주문상품

**Comment by Cheonrihyang** [comment]
mypage_order_payment.jsp > product_order_payment

**Comment by baekchanhyek** [comment]
product_list_page
제품 리스트페이지

main>section>nav : 제품 종류별 이동 링크
main>section>aside>leftside : 제품 필터 기능
main>section>aside>rightside : 최근 본 상품
main>section>section>section>article : 상품 출력 및 상품 이동 링크

product_page
상품 페이지1
main>section>aside : 상품 사진
main>section>section>article : 상품 설명

product_page_2
상품 페이지2
main>nav : 동작버튼 4개가 위치하는곳
main>section>nav : 동작버튼 3개가 위치하는 곳
main>section>article : 리뷰 및 사진 확인

resister.jsp
회원가입 페이지
main>section>nav : 동작버튼 2개 위치
main>section>article : 아이디 비밀번호 등 입력
