### ISSUE TITLE
jsp파일별 동적 기능 정리

### ISSUE THREAD

**Issue by Cheonrihyang** [Cheonrihyang/DengDeng#13]
**<h1>community</h1>**
**community_event_participate_write.jsp**

1. nav의 버튼들을 누르면 각 버튼에 해당하는 게시판으로 이동하는 기능
2. 이전 버튼을 누르면 이전화면으로 돌아가는 기능
3. 등록을 누르면 글이 등록되는 기능

**community_event_participate.jsp**

1. nav의 버튼들을 누르면 각 버튼에 해당하는 게시판으로 이동하는 기능
2. div를 누르면 sns링크로 이동하는 기능
3. 글쓰기를 누르면 글쓰기 화면으로 이동하는 기능
4. 페이지 목록을 누르면 페이지를 이동하는 기능

**community_event.jsp**
1. section-article-div를 클릭하면 해당하는 이벤트로 이동하는 기능

**community_FAQ.jsp**

1. nav의 버튼들을 누르면 각 버튼에 해당하는 게시판으로 이동하는 기능
2. dropdown에서 선택하면 검색의 범위가 바뀌는 기능
3. 검색 버튼을 누르면 텍스트박스의 값이 검색되는 기능
4. 페이지 목록을 누르면 페이지를 이동하는 기능

**community_notice.jsp**

1. nav의 버튼들을 누르면 각 버튼에 해당하는 게시판으로 이동하는 기능
2. dropdown에서 선택하면 검색의 범위가 바뀌는 기능
3. 검색 버튼을 누르면 텍스트박스의 값이 검색되는 기능
4. 페이지 목록을 누르면 페이지를 이동하는 기능

**community_QNA_write.jsp**

1. nav의 버튼들을 누르면 각 버튼에 해당하는 게시판으로 이동하는 기능
2. 이전 버튼을 누르면 이전화면으로 돌아가는 기능
3. 등록을 누르면 글이 등록되는 기능

**community_QNA.jsp**

1. nav의 버튼들을 누르면 각 버튼에 해당하는 게시판으로 이동하는 기능
2. dropdown에서 선택하면 검색의 범위가 바뀌는 기능
3. 검색 버튼을 누르면 텍스트박스의 값이 검색되는 기능
4. 쇼핑하기 버튼을 누르면 쇼핑페이지로 넘어가는 기능
5. 글쓰기를 누르면 글쓰는 페이지로 넘어가는 기능

**Comment by SanghyeonLee97** [comment]
-이상현-

**[공통 사항 mypage]**

1. header-article의 각 영역을 누르면 해당하는 웹페이지로 이동하는 기능
2. section-aside의 각 페이지제목을 누르면 해당하는 웹페이지로 이동하는 기능

**mypage_main.jsp**
1. nav의 기간 버튼(5개) 를 누르면 현재일로부터 해당일까지만 조회해주는 기능
2. nav의 날짜선택으로 원하는 기간을 조회할 수 있는 기능
3. section-section-article 의 왼쪽-중앙 영역을 누르면 해당 상품페이지로 이동하는 기능
4. 배송조회를 누르면 택배사 배송조회로 이동하는 기능
5. 리뷰작성을 누르면 리뷰작성페이지로 이동하는 기능

**mypage_review.jsp**
1. nav의 기간 버튼(5개) 를 누르면 현재일로부터 해당일까지만 조회해주는 기능
2. nav의 날짜선택으로 원하는 기간을 조회할 수 있는 기능
3. section-section-article 의 왼쪽-중앙 영역을 누르면 해당 상품페이지로 이동하는 기능
4. 리뷰작성 여부에 따라 '리뷰 작성' 혹은 '내 리뷰 보기' 로 유동적으로 버튼내용을 알려주는 기능
5. 해당 버튼을 눌렀을떄 해당하는 페이지로 이동하는 기능

**mypage_reserve.jsp**
1. nav의 버튼을 누르면 해당하는 내역만 출력하는 기능

**mypage_coupon.jsp**
- 특별한 기능 없음

**mypage_dibs.jsp**
1. 하트취소를 누르면 하트(찜)이 취소되는 기능
2. 장바구니 담기를 누르면 장바구니에 담기는 기능

**mypage_recently_viewed_items.jsp**
1. 장바구니 담기를 누르면 장바구니에 담기는 기능
2. 바로주문을 누르면 결제페이지로 넘어가는 기능

**mypage_cancel_refund.jsp**
1. 각 버튼을 누르면 해당하는 기능의 창으로 연결되는 기능

**mypage_product_inquiry.jsp**
1. nav의 기간 버튼(5개) 를 누르면 현재일로부터 해당일까지만 조회해주는 기능
2. nav의 날짜선택으로 원하는 기간을 조회할 수 있는 기능
3. 각 열의 아무곳이나 누르면 세부문의내용을 볼 수 있는 기능

**mypage_edit_info.jsp**
1. 비밀번호와 비밀번호 확인이 동일한지 확인하는 기능
2. 우편번호 검색을 누를 시 우편번호 검색하는 창을 띄우는 기능
3. 정보수정을 누를시 정보가 수정되는 기능
4. 회원탈퇴 누를 시 회원탈퇴하는 기능

**mypage_delivery_address.jsp**
1. 수정을 누를시 배송지를 수정할 수 있는 기능
2. 삭제를 누를시 해당 배송지를 삭제하는 기능
3. 배송지 추가하기를 누를 시 새 배송지를 등록하는 기능

**mypage_order_payment**
1. 배송지관리를 눌러 원하는 배송지를 선택할 수 있는 기능
2. 배송메모를 선택하는 기능
3. 쿠폰적용하는 기능
4. 적립금 사용하는 기능
5. 원하는 결제수단을 선택하는 기능 (매우 높은 확률로 구현 불가할듯..?)
7. 결제하기를 누르면 결제창으로 넘어가는 기능

**Comment by L-JUYEON** [comment]
index.jsp 
메인페이지
1.로그인을 누르면 로그인페이지로 이동
2.header의 버튼들을 누르면 각 상품에 해당하는 상품페이지로 이동
3.배너를 누르면 (상품,이벤트 등) 상세페이지로 이동
4.section-article 12개 버튼을 누르면 상품 상세페이지로 이동

login.jsp
로그인페이지
1.로그인 버튼을 누르면 로그인 완료가 되면서 페이지 이동
2.아이디찾기 버튼을 누르면 아이디 찾기 페이지로 이동
3.비밀번호 찾기 버튼을 누르면 비밀번호 찾기 페이지로 이동
4.회원가입을 누르면 회원가입 페이지로 이동

id.jsp
아이디찾기 페이지
1.인증번호 받기를 누르면 해당 이메일로 이메일이 전송되는 기능
2.아이디 찾기를 누르면 고객의 아이디가 나오는 기능
3.로그인을 누르면 로그인 페이지로 이동
4.비밀번호 찾기를 누르면 비밀번호 찾기 페이지로 이동
5.회원가입을 누르면 회원가입 페이지로 이동
6.바로가기 버튼을 누르면 고객문의 페이지로 이동

password.jsp
비밀번호찾기 페이지
1.이메일발송 버튼을 누르면 해당 이메일로 이메일 전송기능
2.비밀번호 찾기를 누르면 고객의 비밀번호가 나오는 기능
3.로그인을 누르면 로그인 페이지로 이동
4.아이디찾기 버튼을 누르면 아이디 찾기 페이지로 이동
5.회원가입을 누르면 회원가입 페이지로 이동

**Comment by Cheonrihyang** [comment]
mypage_order_payment.jsp > product_order_payment

**Comment by baekchanhyek** [comment]
product_list_page
상품 리스트페이지
1. aside>left 항목별 필터 
2. aside>right 최근 본 상품 누르면 해당 상품의 상품페이지로 이동
3. article  상품 누르면 해당 상품의 상품페이지로 이동
4. nav 누르면 해당하는 종류의 상품 페이지 이동
5. ♡누르면 찜,찜 취소

product_page
상품 페이지1
1. 사진 클릭시 사진 확대 기능

product_page_2
상품 페이지2
1.  각 버튼을 누르면 해당하는 기능의 창으로 연결되는 기능
2. 사진 클릭시 사진 확대 기능

resister.jsp
회원가입 페이지
1. 눈 모양을 누르면 비밀번호 표시,사라지는 기능
2. 우편번호 검색을 누르면 주소 조회 되는 기능
3. 취소를 누르면 취소되는 기능
4. 회원가입을 누르면 회원가입 완료 페이지로 이동
