### ISSUE TITLE
필요한 데이터들 뽑기

### ISSUE THREAD

**Issue by Cheonrihyang** [Cheonrihyang/DengDeng#18]
**<h1>커뮤니티</h1>**

**FAQ**
>글번호
카테고리
제목
내용

**QNA+QNAwrite**
>글번호
카테고리
제목
내용
첨부파일
첨부이미지
작성자
등록시간
답변완료여부
운영자답변내용

**Category**
>카테고리번호
카테고리명

**event_participate+write**
>글번호
img주소
url주소
작성자
등록시간

**event**
>이벤트번호
url주소
시작시간
종료시간

@SanghyeonLee97 @L-JUYEON @baekchanhyek

**Comment by L-JUYEON** [comment]
index

로그인정보
카테고리명
배너 상품 이미지,이벤트 이미지  
배너에 들어갈 상세내용+이미지 합친것
하단 상품 이미지
하단 상품 정보(이름,가격 등)

login

고객정보(아이디,비밀번호)

id

고객정보(아이디,이메일)
인증번호
고객 아이디 도출

password

고객정보(이름,아이디,이메일)

**Comment by L-JUYEON** [comment]
index

-상품

이름
이미지
가격
할인가격
번호
재고
판매갯수
원산지
유통기한
내용




-이벤트
이미지
내용
번호
시작일
종료일



login,id,password

-고객
아이디
비밀번호
이메일
고유번호
회원가입일
회원탈퇴일
전화번호
주소
성별
이름
우편번호
생년월일
인증번호
구매내역
찜내역
장바구니내역
쿠폰내역
후기내역


-관리자
아이디
비밀번호
이름
번호

**Comment by SanghyeonLee97** [comment]
### mypage
[공통 사항 **mypage]**
> 고객 이름
> 진행중인 주문/배송
> 미작성 리뷰 갯수
> 적립금
> 쿠폰 갯수

**mypage_main.jsp**
> 상품명
> 상품가격
> 상품수량
> 상품이미지
> 주문번호
> 구매일자

**mypage_review.jsp** + **mypage_write_review.jsp**
> 리뷰번호
> 상품명
> 상품가격
> 상품수량
> 상품이미지
> 구매일자
> 작성한리뷰
> 리뷰내용
> 리뷰 내용
> 별점


**mypage_reserve.jsp**
> 주문번호
> 적립금 구분(적립 or 사용)
> 적립금 금액
> 적립내용

**mypage_coupon.jsp**
> 쿠폰번호
> 쿠폰명
> 할인율/금액
> 제한조건
> 유효기간

**mypage_dibs.jsp**
> 상품명
> 상품가격
> 상품이미지
> 해당 상품 총 하트 갯수
> 찜 여부(내가 눌렀는지 안눌렀는지 boolean타입)

**mypage_recently_viewed_items.jsp**
> 상품명
> 상품가격
> 상품이미지

**mypage_cart.jsp**
> 상품명
> 상품가격
> 상품이미지
> 상품수량

**mypage_cancel_refund.jsp**
> 상품명
> 상품가격
> 상품이미지
> 구매일자

**mypage_product_inquiry.jsp**
> 주문번호
> 상품문의 번호
> 상품문의 제목
> 상품문의 작성일
> 처리상태

**mypage_edit_info.jsp**
> 회원번호
> 아이디
> 비밀번호
> 회원이름
> 전화번호
> 주소
> 우편번호
> 반려견 이름
> 반려견 견종

**mypage_delivery_address.jsp**
> 회원번호
> 배송지 번호
> 아이디
> 회원이름
> 전화번호
> 주소
> 우편번호

### product
**product_order_payment.jsp**
> 회원번호
> 배송지 번호
> 아이디
> 회원이름
> 전화번호
> 주소
> 우편번호
> 적립금
> 주문번호
> 쿠폰번호
> 쿠폰명
> 할인율/금액
> 제한조건
> 유효기간
> 상품번호
> 상품명
> 상품금액
> 상품이미지

**Comment by baekchanhyek** [comment]
product_list_page
상품 리스트페이지

물품이름
물품수량
가격
물품이미지
최근본 상품 기록
찜 여부
제조회사
left-side 필터 기능



product_page
상품 페이지

물품이름
물품수량
가격
물품이미지
제조회사
물품색상
물품 사이즈
제조일자
유통기한
판매갯수


resister.jsp
회원가입 페이지

회원번호
회원이름
아이디
비밀번호 
주소
전화번호
우편번호
반려동물 견종
반려동물 이름
