### ISSUE TITLE
cart.jsp 시멘틱 기능,동적 기능 정리해주세요

### ISSUE THREAD

**Issue by Cheonrihyang** [Cheonrihyang/DengDeng#20]
@SanghyeonLee97

**Comment by SanghyeonLee97** [comment]
### 시멘틱 기능
**mypage_cart.jsp**
장바구니 페이지
1. section-section-header:		해당 페이지의 제목 (ex. 장바구니)
2. section-section-article:		장바구니에 넣은 물품 리스트

### 동적 기능
**mypage_cart.jsp**
> 장바구니의 담은 물품을 취소하는 기능
> 물품을 바로 주문(구매)하는 기능 (물품 1개의 해당)
> 물품리스트 좌측에 체크된 물품만 바로 구매할 수 있는 기능
> 물품을 누르면 상품페이지로 넘어가는 기능
