### ISSUE TITLE
write_review.jsp 시멘틱 기능 정리해주세요

### ISSUE THREAD

**Issue by Cheonrihyang** [Cheonrihyang/DengDeng#21]
@SanghyeonLee97

**Comment by SanghyeonLee97** [comment]
**mypage_write_review.jsp**
리뷰작성 팝업
> section-header			해당 팝업의 제목 (ex_리뷰작성)
> section-article			리뷰평점, 리뷰내용이 들어가는 구역
> section-nav				취소, 확인 버튼이 들어가는 구역
